---
title: "Exercise 7"
author: "문지원"
date: "4/29/2021"
output: html_document
---
# Galton Height Data
## 아버지와 아들의 키의 회귀식을 구해보고 의미를 파악해보시오

### (1) 아버지와 아들의 키의 회귀식 
```{r}
library(dplyr)
library(ggplot2)
Galton <- read.csv('http://www.randomservices.org/random/data/Galton.txt', header=T, sep='\t')
head(Galton)
```

```{r}
df <- Galton %>% 
   filter(Gender== 'M') %>% 
   select(Father, Height) %>% 
   mutate(father= Father*2.54, son= Height*2.54)
head(df)
```
method 1.
```{r}
model <- lm(son ~ father, data= df)
coef(model)
plot(df$father, df$son, xlab= 'father(cm)', ylab= 'son(cm)') +
abline(model, col= 'purple', lwd =3)
```
method 2.
```{r}
ggplot(df, aes(father, son)) +
  geom_point(position='jitter', color='purple', alpha= 0.5) +
  geom_abline(intercept=coef(model)[1], slope=coef(model)[2], 
              color='lightblue', size=1)
```

### (2) 잔차 분석
```{r}
par(mfrow=c(2,2))
plot(model)
```
```{r}
# Residuals vs Fitted 그래프로 미루어 보아 잔차의 산포도가 적절하며, 모형의 선형성에도 문제 없어 회귀분석을 사용한 분석에 문제가 없다.
# Normal Q-Q plot에 의거하여 잔차는 정규분포를 따른다.
# Scale-Location plot을 보았을 때, 빨간 실선이 수평에 가까우므로 등분산성을 만족한다.
# Residuals vs Leverage plot을 보았을 때, 이상치가 조금 있으나, 제거해야할 정도는 아님을 알 수 있다.
```

### (3) 해석
```{r}
summary(model)
```
```{r}
# p-value가 0에 가까운 값으로, 0.05보다 작으므로 유의미하다. 반면, R squared는 0.1513으로 알맞은 모델이나, 설명력이 떨어진다.
```

### (4) Polynomial Regression
```{r}
par(mfrow=c(1,1))
x <- seq(min(df$father), max(df$father), length.out=1000)
colors <- c('darkblue','purple','darkorange','darkgreen')
for (i in 1:4) {
    plot(jitter(df$father), jitter(df$son),
     xlab='father(cm)', ylab='son(cm)')
    model <- lm(son ~ poly(father, i), data= df)
    assign(paste('model', i, sep='.'), model)
    y <- predict(model, data.frame(father=x))
    lines(x, y, col=colors[i], lwd=2)
}
```
```{r}
anova(model.1, model.2, model.3, model.4)
```
```{r}
# p-value가 0.05보다 크기 때문에 다차식 회귀는 무의미하다. 때문에 단순선형회귀가 적합하다.
```

